// Shared Data for VC route

const fundsData = [
  {
    id: 1,
    fundType: "투자조합",
    companyName: "벤처캐피탈 A",
    fundName: "제1호 혁신성장 투자조합",
    registeredAt: "2025-01-10",
    expiredAt: "2032-01-10",
    settlementMonth: 12,
    manager: "홍길동",
    support: "모태펀드",
    purpose: "초기 창업기업 선제적 투자 및 육성",
    industry: "AI, ICT, 빅데이터",
    baseRate: 8.0,
    totalAmount: 12000000000,
  },
  {
    id: 2,
    fundType: "개인투자조합",
    companyName: "스타트업 인베스트",
    fundName: "스타트업 엔젤 매칭펀드",
    registeredAt: "2024-05-15",
    expiredAt: "2030-05-15",
    settlementMonth: 3,
    manager: "이수진",
    support: "자체결성",
    purpose: "시드 단계 스타트업 발굴",
    industry: "핀테크, 커머스",
    baseRate: 5.0,
    totalAmount: 2500000000,
  },
  {
    id: 3,
    fundType: "투자조합",
    companyName: "퓨처벤처스",
    fundName: "퓨처 헬스케어 펀드",
    registeredAt: "2024-11-20",
    expiredAt: "2031-11-20",
    settlementMonth: 12,
    manager: "박준호",
    support: "성장금융",
    purpose: "디지털 헬스케어 기반 기술 투자",
    industry: "바이오, 헬스케어",
    baseRate: 7.5,
    totalAmount: 45000000000,
  },
  {
    id: 4,
    fundType: "PEF",
    companyName: "그로스 파트너스",
    fundName: "그로스 제1호 사모투자합자회사",
    registeredAt: "2023-08-05",
    expiredAt: "2033-08-05",
    settlementMonth: 6,
    manager: "최민서",
    support: "연기금",
    purpose: "중견기업 사업재편 및 스케일업 지원",
    industry: "소부장, 제조테크",
    baseRate: 10.0,
    totalAmount: 150000000000,
  },
  {
    id: 5,
    fundType: "투자조합",
    companyName: "모빌리티 벤처스",
    fundName: "스마트 모빌리티 펀드",
    registeredAt: "2025-02-01",
    expiredAt: "2032-02-01",
    settlementMonth: 12,
    manager: "정우성",
    support: "지자체 매칭",
    purpose: "자율주행 및 미래 모빌리티 인프라",
    industry: "모빌리티, 이차전지",
    baseRate: 6.0,
    totalAmount: 30000000000,
  },
];

const investorsData = [
  {
    id: 1,
    name: "박준호",
    company: "테크벤처 파트너스",
    avatar: "박",
    investments: 42,
    successRate: 85,
    type: "vc",
    stages: ["seed", "pre-a", "series-a"],
    tps: true,
    lips: true,
    tops: false,
    description:
      "딥테크 및 AI 스타트업 전문 투자자입니다. 초기 단계부터 밸류업을 지원합니다.",
    fundDescription: "딥테크 혁신성장 펀드 제3호 (500억)",
    logoUrl: "https://via.placeholder.com/150",
    websiteUrl: "https://techventure.com",
    email: "jh.park@techventure.com",
    totalInvestment: 350.5,
    portfolio: 42,
    avgInvestment: 8.3,
    exitCount: 12,
  },
  {
    id: 2,
    name: "김소연",
    company: "에이전트 인베스트먼트",
    avatar: "김",
    investments: 28,
    successRate: 72,
    type: "accelerator",
    stages: ["seed", "pre-a"],
    tps: false,
    lips: true,
    tops: true,
    description:
      "컨텐츠 및 플랫폼 서비스 전문 액셀러레이터입니다. TIPS 연계 지원이 강점입니다.",
    fundDescription: "컨텐츠 벨류업 시드펀드 (150억)",
    logoUrl: "https://via.placeholder.com/150",
    websiteUrl: "https://agentinv.com",
    email: "sy.kim@agentinv.com",
    totalInvestment: 120.0,
    portfolio: 28,
    avgInvestment: 4.2,
    exitCount: 5,
  },
  {
    id: 3,
    name: "이민수",
    company: "글로벌 브릿지",
    avatar: "이",
    investments: 15,
    successRate: 90,
    type: "overseas",
    stages: ["series-a", "series-b"],
    tps: false,
    lips: false,
    tops: false,
    description:
      "스타트업의 해외 진출과 글로벌 네트워킹을 돕는 글로벌 투자자입니다.",
    fundDescription: "K-스타트업 글로벌 확장 펀드 (1000억)",
    logoUrl: "https://via.placeholder.com/150",
    websiteUrl: "https://globalbridge.vc",
    email: "ms.lee@globalbridge.vc",
    totalInvestment: 800.0,
    portfolio: 15,
    avgInvestment: 53.3,
    exitCount: 3,
  },
  {
    id: 4,
    name: "최윤정",
    company: "그린 임팩트",
    avatar: "최",
    investments: 34,
    successRate: 78,
    type: "vc",
    stages: ["pre-a", "series-a", "series-b"],
    tps: true,
    lips: false,
    tops: false,
    description:
      "ESG 및 임팩트 투자 전문입니다. 지속 가능한 성장을 추구합니다.",
    fundDescription: "ESG 임팩트 펀드 제1호 (300억)",
    logoUrl: "https://via.placeholder.com/150",
    websiteUrl: "https://greenimpact.com",
    email: "yj.choi@greenimpact.com",
    totalInvestment: 210.0,
    portfolio: 34,
    avgInvestment: 6.1,
    exitCount: 7,
  },
  {
    id: 5,
    name: "정성훈",
    company: "엔젤클럽 S",
    avatar: "정",
    investments: 56,
    successRate: 65,
    type: "angel-club",
    stages: ["pre-seed", "seed"],
    tps: false,
    lips: false,
    tops: true,
    description:
      "초기 엔젤 투자 경험이 풍부합니다. BM 고도화와 멘토링을 제공합니다.",
    fundDescription: "엔젤클럽 S 공동투자조합",
    logoUrl: "https://via.placeholder.com/150",
    websiteUrl: "https://angel-s.com",
    email: "sh.jung@angel-s.com",
    totalInvestment: 45.0,
    portfolio: 56,
    avgInvestment: 0.8,
    exitCount: 15,
  },
];

const startupsData = [
  {
    id: 1,
    name: "(주)넥스트AI",
    description:
      "차세대 생성형 AI 솔루션을 개발하여 기업의 업무 효율을 극대화합니다.",
    industry: "ai",
    industryLabel: "AI/빅데이터",
    foundedDate: "2025-01-15",
    location: "서울",
    ceoName: "김철수",
    ceoAge: 32,
    ceoGender: "male",
    certifications: ["venture"],
    website: "https://nextai.example.com",
    email: "contact@nextai.example.com",
    imFile: "im_file.pdf",
    irFile: "ir_file.pdf",
  },
  {
    id: 2,
    name: "(주)그린바이오",
    description: "친환경 신소재를 활용한 바이오 패키징 솔루션을 제공합니다.",
    industry: "bio",
    industryLabel: "바이오/헬스케어",
    foundedDate: "2020-05-20",
    location: "경기",
    ceoName: "이영희",
    ceoAge: 45,
    ceoGender: "female",
    certifications: ["innobiz"],
    website: "https://greenbio.example.com",
    email: "info@greenbio.example.com",
    imFile: null,
    irFile: null,
  },
  {
    id: 3,
    name: "(주)핀테크로드",
    description: "소상공인을 위한 간편 매출 정산 및 자금 관리 플랫폼입니다.",
    industry: "fintech",
    industryLabel: "핀테크",
    foundedDate: "2022-11-10",
    location: "부산",
    ceoName: "박준영",
    ceoAge: 28,
    ceoGender: "male",
    certifications: ["mainbiz", "venture"],
    website: "https://finroad.example.com",
    email: "support@finroad.example.com",
    imFile: "im_sample.pdf",
    irFile: null,
  },
];
